name: Planifolia Core
id: core

stages:
- id: build
  base: ghcr.io/archlinux/archlinux:base
  singlelayer: false
  labels:
    maintainer: nisel11

  modules:
  - name: check-updates
    type: shell
    commands:
      - pacman -Syu --noconfirm

  - name: man
    type: shell
    commands:
      - sed -i "s|NoExtract*|#NoExtract|g" /etc/pacman.conf
      - pacman -Sy --noconfirm man-db
      - mandb -c

  - name: packages-modules
    type: includes
    includes:
      - modules/00-vanilla-abroot.yml
      - modules/00-vanilla-apx.yml
      - modules/00-vanilla-apx-stacks.yml
      - modules/01-kernel.yml
      - modules/02-kernel-version-file.yml
      - modules/03-fswarn.yml
      - modules/04-override-hooks.yml
      - modules/05-firmware.yml
      - modules/10-input-and-locale.yml
      - modules/20-ssh.yml
      - modules/30-utils.yml
      - modules/40-essentials.yml
      - modules/41-move-boot-scripts.yml
      - modules/50-fs.yml
      - modules/60-sound.yml
      - modules/70-compression.yml
      - modules/80-xdg.yml
      - modules/90-network.yml
      - modules/91-iptables.yml
      - modules/100-modules.yml
      - modules/110-fwupd.yml
      - modules/120-fingerprint.yml
      - modules/130-services.yml
      - modules/150-init-executable.yml
      - modules/998-podman-registry.yml
      - modules/999-remove-grub-files.yml

  - name: zram-config
    type: shell
    commands:
      - pacman -Sy --noconfirm zram-generator
      - echo -e "[zram0]\nzram-size = min(ram / 2)\ncompression-algorithm = lz4\n" >> /etc/systemd/zram-generator.conf

  - name: fsguard-runtime-deps
    type: shell
    commands:
      - pacman -Sy --noconfirm minisign squashfs-tools python

  - name: polkit-remember-auth
    type: shell
    commands:
    - sed -ie 's/auth_admin/auth_admin_keep/' /usr/share/polkit-1/actions/org.freedesktop.policykit.policy

  - name: fsguard
    type: fsguard
    FsGuardLocation: "/usr/sbin/FsGuard"
    GenerateKey: true
    FilelistPaths: ["/usr/bin"]

  - name: lock-pacman
    type: shell
    commands:
      - lpkg --lock

  - name: cleanup2
    type: shell
    commands:
      - rm -rf /var/cache/*
      - rm -rf /tmp/*
      - rm -rf /var/tmp/*
      - rm -rf /sources
